doctrine:
    dbal:
        url: 'mysql://%env(DB_USER)%:%env(DB_PASSWORD)%@%env(DB_SERVER)%:%env(DB_PORT)%/%env(DB_NAME)%'
        server_version: '8'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_0900_ai_ci
        types:
            mensageiro_id: MiniPay\Framework\Id\Infrastructure\Doctrine\DBALTypes\IdType
            datetime_immutable: \Carbon\Doctrine\DateTimeImmutableType
            datetime: \Carbon\Doctrine\DateTimeType

    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
