kernel:
  resource: ../../src/Kernel.php
  type: annotation

healthcheck_controllers:
  resource: '../../src/Healthcheck/Infrastructure/Controller'
  type: annotation

core_user_controllers:
  resource: '../../src/Core/User/Infrastructure/Controller'
  type: annotation

#your_package_controllers:
#  resource: '../../src/YourPackage/Infrastructure/Controller'
#  type: annotation
